### PR TITLE
✨ Feature: add a new tool Typescript interface to mock data

### PR DESCRIPTION
**Pull request by arvinxx**
Here it is.

image

### CODE REVIEW

**Comment by arvinxx** [comment]
It seems the same problem with #259

**Review by sophacola — APPROVED** [review]

**Review by pratyushsingha — COMMENTED** [review]
it works very good

**Review by pratyushsingha — APPROVED** [review]
please approve

**Comment by ritz078** [comment]
@arvinxx This is beyond the scope of this project. This project deals with converters and not generators. Thanks for your contribution but will have to close this unfortunately.

**Pull request closed without merging**
