### PR TITLE
CSS to TailwindCSS

### PR DESCRIPTION
**Pull request by miklosme**
~Work in progress~

~*I opened this PR here by accident, I wanted to open it in my fork. 😅*~

The PR is ready for review. I think this transformer at its current form can give good value to its users, however two main things are missing: [variants](https://tailwindcss.com/docs/configuration#variants) support, and support for custom Tailwind [configs](https://tailwindcss.com/docs/configuration).

- Variant support: I want to implement it properly, so I need some time to think on the problem.

 - Config: The [css-to-tailwind](https://github.com/miklosme/css-to-tailwind) package does support any configs, but it requires to run PostCSS, and I need to figure out how to do that in this project properly.

### CODE REVIEW

**Comment by ritz078** [comment]
@miklosme I don't see this as a mistake. 😄

**Comment by ritz078** [comment]
@miklosme Should I close this PR?

**Comment by miklosme** [comment]
hi @ritz078, this pr is ready to review!

**Comment by ritz078** [comment]
@all-contributors please add @miklosme for code.

**Pull request merged**
