### PR TITLE
Fix 500 for json schema to openapi schema

### PR DESCRIPTION
**Pull request by jfsiii**
closes https://github.com/ritz078/transform/issues/247

`@openapi-contrib/json-schema-to-openapi-schema` uses `fs` inside its convert function. Moved conversion to an API route, following example for `typescript-to-json-schema` component & route

https://transform-mjmb43obq-ritz078.vercel.app/json-schema-to-openapi-schema

Screen Shot 2021-02-21 at 10 11 24 AM

### CODE REVIEW

**Comment by jfsiii** [comment]
No luck https://transform-git-fork-jfsiii-patch-1.ritz078.now.sh/json-schema-to-openapi-schema

Screen Shot 2021-02-10 at 10 19 01 AM

@ritz078 Let me know if you have any ideas about the failure or how I can learn more. I don't know what error is occuring, and haven't used vercel/next so I don't know where I might be able to see the message/trace.

**Comment by ritz078** [comment]
It looks like the issue is in https://github.com/wework/json-schema-to-openapi-schema itself.

The PR is not related to the issue. Are you able to run this locally ?

**Comment by jfsiii** [comment]
I ran this locally around and got this error
Screen Shot 2021-02-12 at 11 07 22 AM

I added some logging in [`node_modules` around the `util.promisify`](https://github.com/openapi-contrib/json-schema-to-openapi-schema/blob/e467aa5045f2d58ef4b6ab05fc2c388d1ae3245f/index.js#L8
) and got this in node
Screen Shot 2021-02-12 at 11 19 43 AM

but this in the browser
Screen Shot 2021-02-12 at 11 19 08 AM

`fs.readFile` is `undefined` which makes sense, since we're in the browser.

Not sure if there's an existing pattern for this (e.g. stub `fs`) or if you have other thoughts about how to address it, but at least we know where it's coming from. Or maybe just the _first_ place it's breaking 😄

**Comment by jfsiii** [comment]
@ritz078 wanted to make sure you saw the latest

**Comment by jfsiii** [comment]
Got it! https://transform-mjmb43obq-ritz078.vercel.app/json-schema-to-openapi-schema

Screen Shot 2021-02-21 at 10 11 24 AM

I followed the pattern for `typescript-to-json-schema` and moved the conversion to an API route.

**Comment by jfsiii** [comment]
@ritz078 should be fixed!

**Review by ritz078 — APPROVED** [review]
This is awesome work @jfsiii . 
Thank you for your contribution 🎉

**Comment by ritz078** [comment]
@all-contributors please add @jfsiii for code.

**Pull request merged**
