### PR TITLE
[WIP] npm to yarn

### PR DESCRIPTION
**Pull request by p-racoon**
npm init and install
Was working on this on a case by case basis
but am trying a slightly different approach
trying it with yargs now, will use different handlers

### CODE REVIEW

**Comment by ritz078** [comment]
#### 📝Changed routes:


| [**/npm-to-yarn**](https://transform-git-prasham-npm-to-yarn.ritz078.now.sh/npm-to-yarn) |
|:-:|
|<a href="https://transform-git-prasham-npm-to-yarn.ritz078.now.sh/npm-to-yarn">Screenshot of /npm-to-yarn</a><br /><sup><a href="https://images.weserv.nl?url=microlink-screenshot.nyc3.digitaloceanspaces.com/popTfm666yaJiuBDcmTdS_C_V04_">(view full size)</a> |







Commit 41085afbcdbfce38ea8a2fa07ae4a4154a10f94f (https://transform-git-prasham-npm-to-yarn.ritz078.now.sh).

**Comment by ritz078** [comment]
Don't request a review for a draft PR :)

**Comment by ritz078** [comment]
and you should move the logic to a separate file.

**Comment by p-racoon** [comment]
> and you should move the logic to a separate file.

Yeah sure, will move it to utils.

**Pull request closed without merging**
