### PR TITLE
Feat: new cadence to go transform backend

### PR DESCRIPTION
**Pull request by LemonNekoGH**
Now support whole contract interaction code generation!

### CODE REVIEW

**Comment by ritz078** [comment]
@LemonNekoGH Thanks for your contribution. This looks like code generation more than conversion and very different from Cadence to Go converter we have right now. Am I correct here ?

**Comment by LemonNekoGH** [comment]
Oh, yes, it's a code generator now, it includes simple struct conversion.

**Comment by ritz078** [comment]
transform.tools doesn't aim to be a code generator right now. I will keep this PR open and think about this. Even if we do choose to support it, it shouldn't replace the existing converter.

**Comment by LemonNekoGH** [comment]
Oh, sorry, I ignored the goal of this website. The existing `Cadence to Go` transformer is week, it cannot transform more than one struct in a single text field, the new backend solved this problem.
If need, I can remove the generation of selected code in the picture by provide a option.
image

**Comment by ritz078** [comment]
@LemonNekoGH Sorry for the delay. I agree that seems like a good approach.

**Comment by LemonNekoGH** [comment]
> @LemonNekoGH Sorry for the delay. I agree that seems like a good approach.

That's ok, now i made the changes, please review

**Review by ritz078 — APPROVED** [review]
This looks great. Thank you for your contribution 🎉

**Comment by ritz078** [comment]
@allcontributors please add @LemonNekoGH for code.

**Pull request merged**
