### PR TITLE
Prasham/upgrade to next9.1 src folder

### PR DESCRIPTION
**Pull request by p-racoon**
Upgrade from next 9.0.2 to next 9.1.1
Upgrade from react 16.8.6 to react 16.10.2
Upgrade from react-dom 16.8.6 to react-dom 16.10.2
Move pages to src/pages
Remove deprecated Container component
Move workers to src/workers
Move hooks to src/hooks
Move assets to src/assets
Move styles to src/styles
Move components to src/components
Move constants to src/constants

### CODE REVIEW

**Comment by ritz078** [comment]
There are few conflicts

**Comment by ritz078** [comment]
This PR will need some more work. Will try to fix the issues tomorrow. :)

**Comment by p-racoon** [comment]
> This PR will need some more work. Will try to fix the issues tomorrow. :)

OK

**Comment by ritz078** [comment]
Can you please take a pull and check why worker files are giving 404?

**Pull request closed without merging**
