### PR TITLE
feat: Adding JSON to Java transformation feature

### PR DESCRIPTION
**Pull request by Pooja444**
## Github issue
https://github.com/ritz078/transform/issues/335

## PR explanation

@ritz078  I am adding a JSON to Java transformation feature. I couldn't find any npm libraries that already do this so I used JSON to Kotlin transformation and applied rules to output Java class models.

I applied the below rules -

- Convert `data class <className>(` to `public class <className> {`
- For every variable `val <variableName>: <variableType>,` convert it to `private <variableType> <variableName>;`
- Add constructor, getters and setters for every variable, as is done in standard Java models
- If there's a kotlin typealias (created when the entire JSON object is an array), wrap the object in a class. E.g. for `typealias Root = List<Root2>` it will create a class root with just one list property and its getters, setters
- Append the constructor, getters setters and close the class when a ')' is found, i.e. kotlin data class end has been reached

I tested this locally with a variety of JSON samples and its working perfectly. Some of the samples I tried were from [this](https://stackoverflow.com/questions/10539797/complex-json-nesting-of-objects-and-arrays) StackOverflow answer, in case anyone would like to test this locally

Please review and let me know if any changes are required.

### CODE REVIEW

**Comment by Pooja444** [comment]
@ritz078 also I would like to mention that I have added getters, setters but haven't added a constructor to every class. I can do that too if you would like, please let me know

**Comment by ritz078** [comment]
> I can do that too if you would like, please let me know

You should add it too other users will see it as a bug.

**Comment by Pooja444** [comment]
@ritz078 added the constructor

**Comment by Pooja444** [comment]
@ritz078 I tested for a number of samples, did all fixes and added constructor generation logic. Can you please review and let me know if it looks good? Thank you!

**Review by ritz078 — APPROVED** [review]
Great job. 
Thank you for your contribution 🎉

**Comment by ritz078** [comment]
@all-contributors please add @Pooja444 for code contribution

**Pull request merged**
